# Use an official Flink image as a parent image
FROM flink:1.14.0

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/remotebank-transactions-1.0-SNAPSHOT-backfill-job.jar /app/remotebank-transactions-1.0-SNAPSHOT-backfill-job.jar

# Run the TransactionsMLFeaturesBackfillJob
# CMD ["./bin/flink", "run", "-m", "flink-jobmanager:8081", "/app/remotebank-transactions-1.0-SNAPSHOT-backfill-job.jar"]